version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    reviewers:
      - "drapon"
    assignees:
      - "drapon"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore specific dependencies if needed
      # - dependency-name: "github.com/example/package"
      #   versions: ["1.x", "2.x"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    reviewers:
      - "drapon"
    assignees:
      - "drapon"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    reviewers:
      - "drapon"
    assignees:
      - "drapon"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"